name: wonder
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  http: ^1.4.0
  flutter_secure_storage: ^9.2.4
  logger: ^2.5.0
  tuple: ^2.0.2
  flutter_web_auth_2: ^4.1.0
  shared_preferences: ^2.5.3
  pkce: ^1.1.0+1
  url_launcher: ^6.3.1
  flex_color_scheme: ^8.1.1
  go_router: ^15.1.2
  flutter_riverpod: ^2.6.1
  recase: ^4.1.0
  shimmer: ^3.0.0
  flex_color_picker: ^3.7.1
  hive: ^2.2.3

dev_dependencies:
  test: ^1.25.8
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
