name: wonder
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  http: ^1.4.0
  logger: ^2.5.0
  tuple: ^2.0.2
  flutter_web_auth_2: ^4.1.0
  shared_preferences: ^2.5.3
  pkce: ^1.1.0+1
  url_launcher: ^6.3.1
  flex_color_scheme: ^8.2.0
  go_router: ^15.1.2
  flutter_riverpod: ^2.6.1
  recase: ^4.1.0
  shimmer: ^3.0.0
  flex_color_picker: ^3.7.1
  hive: ^2.2.3
  drop_down_search_field: ^1.1.3
  multi_dropdown: ^3.0.1
  flutter_secure_storage: ^9.2.4
  image_picker: ^1.1.2
  skeletonizer: ^2.0.1
  scrollable_positioned_list: ^0.3.8
  path_provider: ^2.1.5
  uuid: ^4.5.1
  top_snackbar_flutter: ^3.3.0
  dotted_border: ^3.0.1
  auto_size_text_plus: ^3.0.2

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
