workflows:
  build_and_publish:
    name: Build & Publish
    integrations:
      app_store_connect: codemagic
    environment:
      flutter: stable
      groups:
        - google_play
      vars:
        BUILD_NAME: 1.0.$PROJECT_BUILD_NUMBER
        BUILD_NUMBER: $PROJECT_BUILD_NUMBER
      ios_signing:
        distribution_type: app_store # or: ad_hoc | development | enterprise
        bundle_identifier: com.wonder.manage
      android_signing:
        - wonder_android_upload_keystore
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Print build variables to log
        script: |
          echo "BUILD_NAME=$BUILD_NAME"
          echo "BUILD_NUMBER=$BUILD_NUMBER"
      - name: Build AAB
        script:
            flutter build appbundle --build-name=$BUILD_NAME --build-number=$BUILD_NUMBER
#      - name: Build IPA
#        script:
#            flutter build ipa --release --build-name=$BUILD_NAME --build-number=$BUILD_NUMBER --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/app/outputs/**/*.aab
      - build/ios/ipa/*.ipa
    publishing:
#      app_store_connect:
#        auth: integration
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
