name: wonder
description: "Wonder Resources Management."
publish_to: 'none'

version: 1.0.0+4

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  assets:
    path: assets

  http: ^1.4.0
  logger: ^2.5.0
  tuple: ^2.0.2
  flutter_web_auth_2: ^4.1.0
  shared_preferences: ^2.5.3
  pkce: ^1.1.0+1
  url_launcher: ^6.3.1
  flex_color_scheme: ^8.2.0
  go_router: ^15.1.3
  flutter_riverpod: ^2.6.1
  recase: ^4.1.0
  shimmer: ^3.0.0
  flex_color_picker: ^3.7.1
  hive: ^2.2.3
  drop_down_search_field: ^1.1.3
  multi_dropdown: ^3.0.1
  image_picker: ^1.1.2
  skeletonizer: ^2.0.1
  scrollable_positioned_list: ^0.3.8
  path_provider: ^2.1.5
  uuid: ^4.5.1
  dotted_border: ^3.0.1
  auto_size_text_plus: ^3.0.2
  widgetbook: ^3.14.2
  widgetbook_annotation: ^3.5.0
  dropdown_search: ^6.0.2
  deep_collection: ^1.0.2
  flutter_custom_tabs: ^2.4.0
  app_links: ^6.4.0
  path: ^1.9.1
  mime: ^2.0.0
  http_parser: ^4.1.2
  file_saver: ^0.3.0
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  cached_network_image_platform_interface: ^4.1.1
  flutter_secure_storage: ^4.2.1
  flutter_secure_storage_web: ^2.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

dev_dependencies:
  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  widgetbook_generator: ^3.13.0

flutter:
  uses-material-design: true
