name: wonder_widgetbook
description: "Widgetbook for wonder project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  wonder:
    path: ../
  wonder_api:
    path: ../wonder_api
  assets:
    path: ../assets

  flutter_riverpod: ^2.6.1
  widgetbook: ^3.14.2
  widgetbook_annotation: ^3.5.0
  logger: ^2.5.0
  dropdown_search: ^6.0.2

dev_dependencies:
  build_runner: any
  flutter_lints: ^6.0.0
  widgetbook_generator: ^3.13.0

flutter:
  uses-material-design: true
